"""Template engine for project generation."""

from __future__ import annotations

import logging
from pathlib import Path

from .schemas import DirectoryNode, FileNode, OrganizeTemplate, ProjectTemplate

logger = logging.getLogger("filehub")


class TemplateEngine:
    """Engine to scaffold project directory structures."""

    def __init__(self, templates: list[ProjectTemplate] | None = None):
        """Initialize template engine.

        Args:
            templates: List of additional/override templates
        """
        self.templates: dict[str, ProjectTemplate] = {}
        self.organize_templates: dict[str, OrganizeTemplate] = {}
        self._load_default_templates()
        self._load_default_organize_templates()

        if templates:
            for template in templates:
                self.templates[template.name] = template

    def _load_default_templates(self) -> None:
        """Load built-in templates."""
        # Standard EPC Project Template
        structure = DirectoryNode(
            name="root",
            children=[
                DirectoryNode(
                    name="01_Docs",
                    children=[
                        DirectoryNode(name="01_Contracts"),
                        DirectoryNode(name="02_Correspondence"),
                        DirectoryNode(name="03_Meetings"),
                    ],
                ),
                DirectoryNode(
                    name="02_Engineering",
                    children=[
                        DirectoryNode(name="01_Calculations"),
                        DirectoryNode(name="02_Reports"),
                    ],
                ),
                DirectoryNode(
                    name="03_Drawings",
                    children=[
                        DirectoryNode(name="01_DWG"),
                        DirectoryNode(name="02_PDF"),
                        DirectoryNode(name="03_Sketches"),
                    ],
                ),
                DirectoryNode(
                    name="04_Models",
                    children=[
                        DirectoryNode(name="01_Revit"),
                        DirectoryNode(name="02_Navisworks"),
                        DirectoryNode(name="03_IFC"),
                    ],
                ),
                DirectoryNode(name="05_References"),
                DirectoryNode(name="99_Archive"),
            ],
            files=[FileNode(name="README.txt", content="Project structure generated by FileHub.")],
        )

        self.templates["epc_standard"] = ProjectTemplate(
            name="epc_standard", description="Standard EPC project structure", structure=structure
        )

    def get_template(self, name: str) -> ProjectTemplate | None:
        """Get template by name."""
        return self.templates.get(name)

    def list_templates(self) -> list[str]:
        """List available template names."""
        return list(self.templates.keys())

    def scaffold(self, template_name: str, target_dir: Path) -> None:
        """Generate project structure from template.

        Args:
            template_name: Name of the template to use
            target_dir: Root directory for the project

        Raises:
            ValueError: If template not found
            OSError: If filesystem operations fail
        """
        template = self.get_template(template_name)
        if not template:
            raise ValueError(f"Template '{template_name}' not found.")

        if not target_dir.exists():
            target_dir.mkdir(parents=True)
            logger.info("Created project root: %s", target_dir)

        self._create_structure(template.structure, target_dir)
        logger.info("Project scaffolded successfully using template '%s'", template_name)

    def _create_structure(self, node: DirectoryNode, current_path: Path) -> None:
        """Recursively create directory structure."""
        # Create files in current directory
        for file_node in node.files:
            file_path = current_path / file_node.name
            if not file_path.exists():
                file_path.write_text(file_node.content, encoding="utf-8")
                logger.debug("Created file: %s", file_path)
            else:
                logger.debug("Skipped existing file: %s", file_path)

        # Create subdirectories
        for child in node.children:
            child_path = current_path / child.name
            if not child_path.exists():
                child_path.mkdir()
                logger.debug("Created directory: %s", child_path)
            else:
                logger.debug("Skipped existing directory: %s", child_path)

            # Recurse
            self._create_structure(child, child_path)

    # ------------------------------------------------------------------
    # Organize templates (file classification rules)
    # ------------------------------------------------------------------

    def _load_default_organize_templates(self) -> None:
        """Load built-in organize templates."""
        self.organize_templates["epc_structural"] = OrganizeTemplate(
            name="epc_structural",
            description="EPC 구조설계 프로젝트 파일 정리",
            ext_groups={
                "drawings": ["dwg", "dxf", "dwl", "dwl2"],
                "analysis": ["mgb", "out", "msr", "geig", "inp", "tsc2", "msg"],
                "fabrication": ["nc1", "kis"],
                "documents": [
                    "pdf",
                    "doc",
                    "docx",
                    "xlsx",
                    "xls",
                    "hwp",
                    "hwpx",
                    "txt",
                    "rtf",
                    "ppt",
                    "pptx",
                ],
                "images": ["jpg", "jpeg", "png", "gif", "bmp", "tif", "tiff"],
                "models": ["ifc", "rvt", "nwd", "nwc"],
            },
            rules=[
                {
                    "name": "EPC 확장자 분류",
                    "action": "move",
                    "trigger": "always",
                    "target": "{ext_group}/{ext_no_dot}",
                    "conflict": "rename",
                },
            ],
            default_group="others",
            folder_template="epc_standard",
        )

        self.organize_templates["general"] = OrganizeTemplate(
            name="general",
            description="범용 파일 정리 (확장자 기반)",
            ext_groups={
                "drawings": ["dwg", "dxf"],
                "documents": [
                    "pdf",
                    "doc",
                    "docx",
                    "txt",
                    "ppt",
                    "pptx",
                    "xls",
                    "xlsx",
                    "rtf",
                    "hwp",
                    "hwpx",
                ],
                "images": ["jpg", "jpeg", "png", "gif", "bmp", "tif", "tiff", "webp"],
                "models": ["ifc", "rvt", "nwd", "nwc"],
            },
            rules=[
                {
                    "name": "확장자 분류",
                    "action": "move",
                    "trigger": "always",
                    "target": "{ext_group}/{ext_no_dot}",
                    "conflict": "rename",
                },
            ],
        )

    def load_organize_templates(self, templates: list[OrganizeTemplate]) -> None:
        """Register additional organize templates (from user config).

        User-supplied templates override built-in templates with the same name.
        """
        for tmpl in templates:
            self.organize_templates[tmpl.name] = tmpl

    def get_organize_template(self, name: str) -> OrganizeTemplate | None:
        """Get organize template by name."""
        return self.organize_templates.get(name)

    def list_organize_templates(self) -> list[str]:
        """List available organize template names."""
        return list(self.organize_templates.keys())
